=== sedofihope/VTSG/src/templates/dtd/complexities.dtd
<!-- complexities.dtd for VTSG -->
<!-- *modified "Thu Sep 12 10:47:30 2024" *by "Paul E. Black" -->
<!ELEMENT root (conditions+, complexities+)>
<!ELEMENT conditions (condition+)>
<!ELEMENT condition (imports?, code, value)>
<!ATTLIST condition id CDATA #REQUIRED>
<!ELEMENT value (#PCDATA)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT complexities (complexity+)>
<!ELEMENT complexity (imports?, code, body*)>
<!ELEMENT body (#PCDATA)>
<!ATTLIST complexity id CDATA #REQUIRED>
<!ATTLIST complexity type CDATA #REQUIRED>
<!ATTLIST complexity group CDATA #REQUIRED>
<!ATTLIST complexity executed CDATA #REQUIRED>
<!ATTLIST complexity need_condition CDATA #IMPLIED>
<!ATTLIST complexity need_id CDATA #IMPLIED>
<!ATTLIST complexity in_out_var CDATA #IMPLIED>
<!ATTLIST complexity indirection CDATA #IMPLIED>
<!ELEMENT imports (import*)>
<!ELEMENT import (#PCDATA)>
<!-- end of complexities.dtd -->

=== sedofihope/VTSG/tests/templates/test014/complexities.xml
<?xml version = "1.0" standalone="no"?>
<!DOCTYPE root SYSTEM "../dtd/complexities.dtd">
<root>
    <conditions>
        <condition id="1">
            <code>1==1</code>
            <value>True</value>
        </condition>
    </conditions>

    <complexities>
        <complexity id="8" type="if" group="conditionals" executed="0" need_condition="1">
            <code>
if({{ condition }}):
INDENT
    {}
DEDENT
elif(not {{ condition }}):
INDENT
    {}
DEDENT
else:
INDENT
    {{ placeholder }}
DEDENT
            </code>
        </complexity>

        <!--Conditional and unconditional loops -->

        <complexity id="12" type="while" group="loops" executed="1" need_condition="1">
            <code>
while True:
INDENT
    {{ placeholder }}
    if({{ condition }}):
    INDENT
        break
    DEDENT
DEDENT
            </code>
        </complexity>

    </complexities>
</root>

=== sedofihope/VTSG/tests/templates/test017/complexities.xml
<?xml version = "1.0" standalone="no"?>
<!-- *created  "Fri Sep  9 16:00:36 2022" *by "Paul E. Black" -->
<!-- *modified "Fri Sep  9 16:13:56 2022" *by "Paul E. Black" -->
<!DOCTYPE root SYSTEM "../dtd/complexities.dtd">
<root>
    <conditions>
        <condition id="1">
            <code>1==1</code>
            <value>True</value>
        </condition>
    </conditions>

    <complexities>
        <complexity id="12" type="while" group="loops" executed="1" need_condition="1">
            <code>
        while True:
	INDENT
                {{ placeholder }}
                if({{ condition }}):
		INDENT
                        break
		ENDINDENT
                break
	ENDINDENT
            </code>
        </complexity>
    </complexities>
</root>

<!-- end of complexities.xml -->

=== sedofihope/VTSG/src/templates/py/complexities.xml
<?xml version = "1.0" standalone="no"?>
<!DOCTYPE root SYSTEM "../dtd/complexities.dtd">
<root>
    <conditions>
        <!--
        <condition id="">
            <code></code>
            <value></value>
        </condition>
        -->
        <condition id="1">
            <code>1==1</code>
            <value>True</value>
        </condition>

        <condition id="2">
            <code>1==0</code>
            <value>False</value>
        </condition>

        <condition id="3">
            <code>(4+2&lt;=42)</code>
            <value>True</value>
        </condition>

        <condition id="4">
            <code>(4+2>=42)</code>
            <value>False</value>
        </condition>

        <condition id="5">
            <code>(math.pow(4, 2)&lt;=42)</code>
            <value>True</value>
        </condition>

        <condition id="6">
            <code>(math.pow(4, 2)>=42)</code>
            <value>False</value>
        </condition>

        <condition id="7">
            <code>(math.sqrt(42)&lt;=42)</code>
            <value>True</value>
        </condition>

        <condition id="8">
            <code>(math.sqrt(42)>=42)</code>
            <value>False</value>
       </condition>

        <!-- TODO add other conditions-->
    </conditions>

    <complexities>
        <!--
        <complexity id="" type="" group="" executed="" in_out_var="i" indirection="" need_id="">
            <code></code>
            <body></body>
        </complexity>
        -->
        <!-- Conditional branching -->
        <!-- if statements-->

        <complexity id="1" type="if" group="conditionals" executed="condition">
            <code>
        if {{ condition }}:
	INDENT
                {{ placeholder }}
	ENDINDENT
            </code>
        </complexity>

        <complexity id="2" type="if" group="conditionals" executed="condition">
            <code>
        if {{ condition }}:
	INDENT
                {{ placeholder }}
	ENDINDENT
        else:
	INDENT
                {}
	ENDINDENT
            </code>
        </complexity>

        <complexity id="3" type="if" group="conditionals" executed="not_condition">
            <code>
        if {{ condition }}:
	INDENT
                {}
	ENDINDENT
        else:
        INDENT
                {{ placeholder }}
        ENDINDENT
            </code>
        </complexity>

        <complexity id="4" type="if" group="conditionals" executed="condition">
            <code>
        if {{ condition }}:
	INDENT
                {{ placeholder }}
	ENDINDENT
        elif not {{ condition }}:
	INDENT
                {}
	ENDINDENT
            </code>
        </complexity>

        <complexity id="5" type="if" group="conditionals" executed="not_condition">
            <code>
        if {{ condition }}:
	INDENT
                {}
	ENDINDENT
        elif not {{ condition }}:
	INDENT
                {{ placeholder }}
	ENDINDENT
            </code>
        </complexity>

        <complexity id="6" type="if" group="conditionals" executed="condition">
            <code>
        if {{ condition }}:
	INDENT
                {{ placeholder }}
	ENDINDENT
        elif not {{ condition }}:
	INDENT
                {}
	ENDINDENT
        else:
        INDENT
                {}
        ENDINDENT
            </code>
        </complexity>

        <complexity id="7" type="if" group="conditionals" executed="not_condition">
            <code>
        if {{ condition }}:
	INDENT
                {}
	ENDINDENT
        elif not {{ condition }}:
	INDENT
                {{ placeholder }}
	ENDINDENT
        else:
        INDENT
                {}
        ENDINDENT
            </code>
        </complexity>

        <complexity id="8" type="if" group="conditionals" executed="0">
            <code>
	if {{condition}}:
	INDENT
                {}
	ENDINDENT
        elif not {{condition}}:
	INDENT
                {}
	ENDINDENT
        else:
        INDENT
	    {{placeholder}}
	ENDINDENT
            </code>
        </complexity>

        <!-- Switch cases  -->
        <complexity id="11" type="switch" group="conditionals" executed="0">
            <code>
	match 6:
	INDENT
            case 6:
	    INDENT
                pass
	    ENDINDENT
            case _:
	    INDENT
                {{ placeholder }}
	    ENDINDENT
	ENDINDENT
            </code>
        </complexity>

        <complexity id="12" type="switch" group="conditionals" executed="1">
            <code>
	match 6:
	INDENT
            case 6:
	    INDENT
                {{ placeholder }}
	    ENDINDENT
            case _:
	    INDENT
                pass
	    ENDINDENT
	ENDINDENT
            </code>
        </complexity>

        <!--Conditional and unconditional loops -->

        <complexity id="20" type="while" group="loops" executed="condition">
            <code>
        while {{ condition }}:
	INDENT
                {{ placeholder }}
                break
	ENDINDENT
            </code>
        </complexity>

        <complexity id="21" type="while" group="loops" executed="1" need_condition="1">
            <code>
        while True:
	INDENT
                {{ placeholder }}
                if {{ condition }}:
		INDENT
                        break
		ENDINDENT
                break
	ENDINDENT
            </code>
        </complexity>

        <complexity id="22" type="for" group="loops" executed="1" need_id="1">
            <code>
        i_{{id}} = 1
        for x in range(0, i_{{id}}):
	INDENT
                {{ placeholder }}
	ENDINDENT
            </code>
        </complexity>

        <complexity id="23" type="foreach" group="loops" executed="1" need_id="1" in_out_var="in">
            <code>
        # Declaring an array
        arr_{{ id }} = []

        # Storing value in array element
        arr_{{ id }}.append(None)
        arr_{{ id }}.append(None)
        arr_{{ id }}.append(None)
        arr_{{ id }}.append({{ in_var_name }})

        for val_{{id}} in arr_{{ id }}:
	INDENT
            if val_{{ id }}!=None:
	    INDENT
                {{ out_var_name }} = val_{{ id }}
                {{ placeholder }}
	    ENDINDENT
	ENDINDENT
            </code>
        </complexity>

        <!-- Unconditional jumps -->
	<!-- not supported in Python -->

        <!-- Functions -->
        <complexity id="50" type="function" group="functions" executed="1" in_out_var="traversal" indirection="1" need_id="1">
            <code>{{out_var_name}} = {{call_name}}({{in_var_name}})</code>
            <body>
def {{call_name}}( param_{{id}} ):
INDENT
        {{local_var}}
        {{in_var_name}} = param_{{id}}
        {{ placeholder }}
        return {{out_var_name}}
ENDINDENT

            </body>
        </complexity>

        <complexity id="51" type="function" group="functions" executed="1" in_out_var="in" indirection="1" need_id="1">
            <code>
        {{out_var_name}} = {{call_name}}({{in_var_name}})
        {{ placeholder}}
            </code>
            <body>
def {{call_name}}( param_{{id}} ):
INDENT
        return param_{{id}}
ENDINDENT

            </body>
        </complexity>

        <complexity id="52" type="function" group="functions" executed="1" in_out_var="out" indirection="1" need_id="1">
            <code>
        {{ placeholder}}
        {{out_var_name}} = {{call_name}}({{in_var_name}})
            </code>
            <body>
def {{call_name}}( param_{{id}} ):
INDENT
        return param_{{id}}
ENDINDENT

            </body>
        </complexity>

        <!-- Classes -->
        <complexity id="70" type="class" group="classes" executed="1" in_out_var="traversal" need_id="1" indirection="1">
            <code>
        var_{{id}} = {{call_name}}({{in_var_name}});
        {{out_var_name}} = var_{{id}}.get_var_{{id}}();
            </code>
            <body>
'''
{{comments}}
'''

{{ imports }}

{{static_methods}}

class {{call_name}}:
INDENT
        def __init__(self,{{in_var_name}}_{{id}}):
	INDENT
                self.var_{{id}} = {{in_var_name}}_{{id}}
	ENDINDENT

        def  get_var_{{id}}(self):
	INDENT
                {{local_var}}
                {{in_var_name}} = var_{{id}}
                {{ placeholder}}
                return {{out_var_name}}
	ENDINDENT
ENDINDENT
            </body>
        </complexity>

        <complexity id="71" type="class" group="classes" executed="1" in_out_var="in" need_id="1" indirection="1">
            <code>
        var_{{id}} = {{call_name}}({{in_var_name}})
        {{out_var_name}} = var_{{id}}.get_var_{{id}}()
        {{placeholder}}
            </code>
            <body>
'''
{{comments}}
'''
               
class {{call_name}}:
INDENT
        def __init__(self, param):
	INDENT
                self.var_{{id}} = param
	ENDINDENT

        def get_var_{{id}}(self):
	INDENT
                return self.var_{{id}}
	ENDINDENT

ENDINDENT
            </body>
        </complexity>

        <complexity id="72" type="class" group="classes" executed="1" in_out_var="out" need_id="1" indirection="1">
            <code>
        {{placeholder}}
        var_{{id}} = {{call_name}}({{in_var_name}})
        {{out_var_name}} = var_{{id}}.get_var_{{id}}()
            </code>
            <body>
'''
{{comments}}
'''

class {{call_name}}:
INDENT
        def __init__(self,param):
	INDENT
                self.var_{{id}} = param
	ENDINDENT
    
        def get_var_{{id}}(self):
	INDENT
                return self.var_{{id}}
	ENDINDENT
ENDINDENT
            </body>
        </complexity>
    </complexities>
</root>

=== sedofihope/VTSG/src/templates/test011/complexities.xml
<?xml version = "1.0" standalone="no"?>
<!DOCTYPE root SYSTEM "../dtd/complexities.dtd">
<!-- *modified "Fri Sep 23 12:20:31 2022" *by "Paul E. Black" -->
<root>
    <conditions>
        <condition id="one">
            <code>1==1</code>
            <value>True</value>
        </condition>
    </conditions>

    <complexities>
        <complexity id="eight" type="if" group="conditionals" executed="0">
            <code>
if({{ condition }}):
    {}
elif(not {{ condition }}):
    {}
else:
    {{ placeholder }}
            </code>
        </complexity>

        <!--Conditional and unconditional loops -->

        <complexity id="12" type="while" group="loops" executed="1" need_condition="1">
            <code>
while True:
    {{ placeholder }}
    if({{ condition }}):
        break
            </code>
        </complexity>

    </complexities>
</root>

=== sedofihope/VTSG/src/templates/test014/complexities.xml
<?xml version = "1.0" standalone="no"?>
<!DOCTYPE root SYSTEM "../dtd/complexities.dtd">
<root>
    <conditions>
        <condition id="1">
            <code>1==1</code>
            <value>True</value>
        </condition>
    </conditions>

    <complexities>
        <complexity id="8" type="if" group="conditionals" executed="0">
            <code>
if({{ condition }}):
INDENT
    {}
ENDINDENT
elif(not {{ condition }}):
INDENT
    {}
ENDINDENT
else:
INDENT
    {{ placeholder }}
ENDINDENT
            </code>
        </complexity>

        <!--Conditional and unconditional loops -->

        <complexity id="12" type="while" group="loops" executed="1" need_condition="1">
            <code>
while True:
INDENT
    {{ placeholder }}
    if({{ condition }}):
    INDENT
        break
    ENDINDENT
ENDINDENT
            </code>
        </complexity>

    </complexities>
</root>

=== sedofihope/VTSG/tests/templates/example/complexities.xml
<?xml version = "1.0" standalone="no"?>
<!-- *created  "Wed Sep 21 16:03:47 2022" *by "Paul E. Black" -->
<!-- *modified "Wed Sep 21 17:00:12 2022" *by "Paul E. Black" -->
<!DOCTYPE root SYSTEM "../dtd/complexities.dtd">
<!-- "language" for example used in the manual -->
<root>
    <conditions>
        <condition id="7">
            <code>(Math.Sqrt(42)&lt;=42)</code>
            <value>True</value>
        </condition>
    </conditions>

    <complexities>
        <complexity id="11" type="while" group="loops" executed="condition">
            <code>
                while({{ condition }}){
                    {{ placeholder }}
                    break;
                }
            </code>
        </complexity>

        <complexity id="20" type="class" group="classes" executed="1" in_out_var="traversal" need_id="1" indirection="1">
            <code>
                {{call_name}} var_{{id}} = new {{call_name}}({{in_var_name}});
                {{out_var_name}} = var_{{id}}.get_var_{{id}}();
            </code>
            <body>
                /*
                {{comments}}
                */
                /*
                {{license}}
                */
                {{ imports }}
                namespace default_namespace{
                    class {{call_name}}{

                        {{in_var_type}} var_{{id}};

                        public {{call_name}}({{in_var_type}} {{in_var_name}}_{{id}}){
                            var_{{id}} = {{in_var_name}}_{{id}};
                        }

                        public {{out_var_type}} get_var_{{id}}(){
                            {{local_var}}
                            {{in_var_name}} = var_{{id}};
                            {{ placeholder}}
                            return {{out_var_name}};
                        }

                        {{static_methods}}
                    }
                }
            </body>
        </complexity>
    </complexities>
</root>
<!-- end of complexities.xml -->

=== sedofihope/VTSG/tests/templates/test027/complexities.xml
<?xml version = "1.0" standalone="no"?>
<!DOCTYPE root SYSTEM "../dtd/complexities.dtd">
<!-- *created  "Fri Jan 19 16:44:33 2024" *by "Paul E. Black" -->
<!-- *modified "Tue Feb 13 10:12:03 2024" *by "Paul E. Black" -->
<root>
    <conditions>
        <!--
        <condition id="">
            <code></code>
            <value></value>
        </condition>
        -->
	<!-- test purpose: condition with no import -->
        <condition id="2">
            <code>1==0</code>
            <value>False</value>
        </condition>

	<!-- test purpose: condition with an import -->
        <condition id="5">
	    <imports>
	      <import>math</import>
	    </imports>
            <code>(math.pow(4, 2)&lt;=42)</code>
            <value>True</value>
        </condition>

    </conditions>

    <complexities>
        <!--
        <complexity id="" type="" group="" executed="" in_out_var="i" indirection="" need_id="">
            <code></code>
            <body></body>
        </complexity>
        -->
        <!-- Conditional branching -->
        <!-- if statements-->

	<!-- test purpose: complexity with two imports -->
        <complexity id="1" type="if" group="conditionals" executed="condition">
	    <imports>
	      <import>random</import>
	      <import>string</import>
	    </imports>
            <code>
	      # use Python random and string to test imports.  Both tests are False
	      # so they are evaluated, but don't affect the value of the condition.
              if random.randint(0, 100) &gt; 200 or 'A' in string.digits or {{condition}}:
	      INDENT
                  {{ placeholder }}
	      DEDENT
            </code>
        </complexity>

	<!-- test purpose: complexity that does NOT import anything -->
        <complexity id="13" type="switch" group="conditionals" executed="1">
            <code>
	match 7:
	INDENT
            case 6:
	    INDENT
                pass
	    DEDENT
            case _:
	    INDENT
                {{ placeholder }}
	    DEDENT
	DEDENT
            </code>
        </complexity>

	<!-- test purpose: body import, that is, library import in <body> -->
        <complexity id="70bi" type="class" group="classes" executed="1" in_out_var="traversal" need_id="1" indirection="1">
	    <imports>
	      <!-- "as module_1" must be generated by VTSG, to get number right -->
	      <import>{{body_file}}</import>
	    </imports>
            <code>
        var_{{id}} = {{body_file}}.{{call_name}}({{in_var_name}})
        {{out_var_name}} = var_{{id}}.get_var_{{id}}()
            </code>
            <body>
'''
{{comments}}
'''
'''
{{ license }}
'''

import collections
{{ stdlib_imports }}

{{static_methods}}

class {{call_name}}:
INDENT
        def __init__(self, {{in_var_name}}_{{id}}):
	INDENT
                self.var_{{id}} = {{in_var_name}}_{{id}}
	DEDENT

        def  get_var_{{id}}(self):
	INDENT
            {{local_var}}
	    # use Python collections to test imports
	    de_queue = collections.deque()
            de_queue.append(self.var_{{id}})
            {{in_var_name}} = de_queue.pop()
            {{ placeholder}}
            return {{out_var_name}}
	DEDENT
DEDENT
            </body>
        </complexity>

	<!-- test purpose: code import, that is, library import where <code> is
	     placed.  Also, both library import and class or module import -->
        <complexity id="70ci" type="class" group="classes" executed="1" in_out_var="traversal" need_id="1" indirection="1">
	    <imports>
	      <import>collections</import>
	      <!-- "as module_1" must be generated by VTSG, to get number right -->
	      <import>{{body_file}}</import>
	    </imports>
            <code>
	      # use Python collections to test imports
	      de_queue = collections.deque()
              de_queue.append({{body_file}}.{{call_name}}({{in_var_name}}))
              var_{{id}} = de_queue.pop()
              {{out_var_name}} = var_{{id}}.get_var_{{id}}()
            </code>
            <body>
'''
{{comments}}
'''
'''
{{ license }}
'''

{{ stdlib_imports }}

{{static_methods}}

class {{call_name}}:
INDENT
        def __init__(self, {{in_var_name}}_{{id}}):
	INDENT
                self.var_{{id}} = {{in_var_name}}_{{id}}
	DEDENT

        def  get_var_{{id}}(self):
	INDENT
            {{local_var}}
            {{in_var_name}} = self.var_{{id}}
            {{ placeholder}}
            return {{out_var_name}}
	DEDENT
DEDENT
            </body>
        </complexity>
    </complexities>
</root>
<!-- end of complexities.xml -->

=== sedofihope/VTSG/tests/templates/test025/complexities.xml
<?xml version = "1.0" standalone="no"?>
<!DOCTYPE root SYSTEM "../dtd/complexities.dtd">
<!-- *created  "Fri Apr 14 09:31:25 2023" *by "Paul E. Black" -->
<!-- *modified "Fri Apr 14 11:55:10 2023" *by "Paul E. Black" -->
<root>
    <conditions>
        <condition id="1">
            <code>1==1</code>
            <value>True</value>
        </condition>

    </conditions>

    <complexities>
        <complexity id="1" type="if" group="conditionals" executed="condition">
            <code>
        if {{ condition }}:
	INDENT
            {{ placeholder }}
	DEDENT
            </code>
        </complexity>

    </complexities>
</root>
