=== sedofihope/VTSG/src/templates/dtd/file_template.dtd
<!-- file_template.dtd for VTSG -->
<!-- *modified "Thu Sep 12 11:10:54 2024" *by "Paul E. Black" -->
<!ELEMENT template (file_extension, comment, syntax, variables, imports?, code)>
<!ATTLIST template name CDATA #REQUIRED>
<!ELEMENT file_extension (#PCDATA)>
<!ELEMENT comment (open, close, inline)>
<!ELEMENT open (#PCDATA)>
<!ELEMENT close (#PCDATA)>
<!ELEMENT inline (#PCDATA)>
<!ELEMENT syntax (statement_terminator, indent?, import_code)>
<!ELEMENT statement_terminator (#PCDATA)>
<!ELEMENT indent (#PCDATA)>
<!ELEMENT import_code (#PCDATA)>
<!ELEMENT variables (variable*)>
<!ATTLIST variables prefix CDATA #REQUIRED>
<!ELEMENT variable EMPTY>
<!ATTLIST variable type CDATA #REQUIRED>
<!ATTLIST variable code CDATA #REQUIRED>
<!ATTLIST variable init CDATA #REQUIRED>
<!ELEMENT imports (import*)>
<!ELEMENT import (#PCDATA)>
<!ELEMENT code (#PCDATA)>
<!-- end of file_template.dtd -->

=== sedofihope/VTSG/src/templates/cs/file_template.xml
<?xml version = "1.0" standalone="no"?>
<!DOCTYPE template SYSTEM "../dtd/file_template.dtd">

<template name="Csharp">
    <file_extension>cs</file_extension>
    <comment>
        <open>/*</open>
        <close>*/</close>
        <inline>//</inline>
    </comment>
    <syntax>
      <statement_terminator>;</statement_terminator>
      <import_code>using {{import_file}};</import_code>
    </syntax>
    <variables prefix="">
        <variable type="int" code="int" init="0"/>
        <variable type="string" code="string" init="null"/>
    </variables>
    <code>
/*
{{comments}}
*/

/*
{{license}}
*/
{{stdlib_imports}}
namespace default_namespace{
    class {{main_name}}{
        public static void Main(string[] args){
            {{local_var}}
            {{input_content}}
            {{filtering_content}}
            {{sink_content}}
            {{exec_queries_content}}
        }
        {{static_methods}}
    }
}
        </code>
</template>

=== sedofihope/VTSG/src/templates/test012/file_template.xml
<?xml version = "1.0" standalone="no"?>
<!DOCTYPE template SYSTEM "../dtd/file_template.dtd">

<template name="test012">
    <file_extension>py</file_extension>
    <comment>
        <open>'''</open>
        <close>'''</close>
        <inline>#</inline>
    </comment>
    <syntax>
    </syntax>
    <namespace></namespace>
    <variables prefix="" import_code="import {{import_file}}">
        <variable type="int" code="" init="0"/>
        <variable type="string" code="" init="None"/>
	<variable type="bool" code="" init="False"/>
	<variable type="float" code="" init="0.0"/>
    </variables>
    <imports>
        <import>sys</import>
    </imports>
    <code>
'''
  Test 2 of 4 for statement_terminator
  ang-syntax-ang, but no ang-statement_terminator-ang
'''
'''
{{ comments }}
'''

'''
{{ license }}
'''
{{ stdlib_imports }}

def main():
        {{ local_var }}
    
        {{ input_content }}

        {{ filtering_content }}

        {{ sink_content }}
    
        <!--{{ exec_queries_content }}-->

main()
{{ static_methods }}
    </code>
</template>

=== sedofihope/VTSG/tests/templates/test006/file_template.xml
<?xml version = "1.0" standalone="no"?>
<!DOCTYPE template SYSTEM "../dtd/file_template.dtd">
<!--  *created "Tue Nov  1 16:08:28 2022" *by "Paul E. Black" -->
<!-- *modified "Tue Nov  1 16:08:52 2022" *by "Paul E. Black" -->

<template name="test006">
    <file_extension>py</file_extension>
    <comment>
        <open>'''</open>
        <close>'''</close>
        <inline>#</inline>
    </comment>
    <syntax>
      <!-- If language doesn't have a terminator, leave empty-->
      <statement_terminator></statement_terminator>
      <!-- Insert desired indentation level using spaces-->
      <indent>        </indent>
    </syntax>
    <namespace></namespace>
    <variables prefix="" import_code="import {{import_file}}">
        <variable type="int" code="" init="0"/>
        <variable type="string" code="" init="None"/>
	<variable type="bool" code="" init="False"/>
	<variable type="float" code="" init="0.0"/>
    </variables>
    <imports>
        <import>sys</import>
        <import>math</import>
    </imports>
    <code>
'''
  Test invalid empty exec_type in sink
'''
'''
{{ comments }}
'''

'''
{{ license }}
'''
{{ stdlib_imports }}

{{ static_methods }}


def main():
INDENT
    {{local_var}}
    {{input_content}}
    {{filtering_content}}
    {{sink_content}}
    {{exec_queries_content}}
DEDENT

if __name__ == '__main__':
        main()
    </code>
</template>

=== sedofihope/VTSG/tests/templates/test001/file_template.xml
<?xml version = "1.0" standalone="no"?>
<!DOCTYPE template SYSTEM "../dtd/file_template.dtd">
<!--  *created "Wed Oct 12 08:41:40 2022" *by "Paul E. Black" -->
<!-- *modified "Tue Aug  1 13:35:56 2023" *by "Paul E. Black" -->

<template name="test001">
    <file_extension>py</file_extension>
    <comment>
        <open>'''</open>
        <close>'''</close>
        <inline>#</inline>
    </comment>
    <syntax>
      <!-- If language doesn't have a terminator, leave empty-->
      <statement_terminator></statement_terminator>
      <!-- Insert desired indentation level using spaces-->
      <indent>        </indent>
      <import_code>import {{import_file}}</import_code>
    </syntax>
    <variables prefix="">
        <variable type="int" code="" init="0"/>
        <variable type="string" code="" init="None"/>
	<variable type="bool" code="" init="False"/>
	<variable type="float" code="" init="0.0"/>
    </variables>
    <imports>
        <import>sys</import>
        <import>math</import>
    </imports>
    <code>
'''
  Test no string in angle-import-angle angle-/import-angle
'''
'''
{{ comments }}
'''

'''
{{ license }}
'''
{{ stdlib_imports }}

{{ static_methods }}


def main():
INDENT
    {{local_var}}
    {{input_content}}
    {{filtering_content}}
    {{sink_content}}
    {{exec_queries_content}}
DEDENT

if __name__ == '__main__':
        main()
    </code>
</template>

=== sedofihope/VTSG/tests/templates/test010/file_template.xml
<?xml version = "1.0" standalone="no"?>
<!DOCTYPE template SYSTEM "../dtd/file_template.dtd">
<!-- *modified "Wed Feb 23 12:48:24 2022" *by "Paul E. Black" -->

<template name="test010">
    <file_extension>py</file_extension>
    <comment>
        <open>'''</open>
        <close>'''</close>
        <inline>#</inline>
    </comment>
    <syntax>
      <!-- If language doesn't have a terminator, leave empty-->
      <statement_terminator></statement_terminator>
      <!-- Insert desired indentation level using spaces-->
      <indent>        </indent>
    </syntax>
    <namespace></namespace>
    <variables prefix="" import_code="import {{import_file}}">
        <variable type="int" code="" init="0"/>
        <variable type="string" code="" init="None"/>
	<variable type="bool" code="" init="False"/>
	<variable type="float" code="" init="0.0"/>
    </variables>
    <imports>
        <import>sys</import>
        <import>math</import>
    </imports>
    <code>
'''
  Test an unsafe case with NO curly-curly-flaw-curly-curly line.
  Test unusual indentation: tab space tab
'''
'''
{{ comments }}
'''

'''
{{ license }}
'''
{{ stdlib_imports }}

{{ static_methods }}


def main():
	 	{{local_var}}
	 	{{input_content}}
{{filtering_content}}
{{sink_content}}
{{exec_queries_content}}

if __name__ == '__main__':
        main()
    </code>
</template>

=== sedofihope/VTSG/tests/templates/test008/file_template.xml
<?xml version = "1.0" standalone="no"?>
<!DOCTYPE template SYSTEM "../dtd/file_template.dtd">
<!-- *created  "Wed Aug  2 10:24:04 2023" *by "Paul E. Black" -->
<!-- *modified "Wed Aug  2 10:25:16 2023" *by "Paul E. Black" -->

<!-- missing ang-syntax-ang section -->

<template name="test008">
    <file_extension>py</file_extension>
    <comment>
        <open>'''</open>
        <close>'''</close>
        <inline>#</inline>
    </comment>
    <variables prefix="">
        <variable type="int" code="" init="0"/>
        <variable type="string" code="" init="None"/>
	<variable type="bool" code="" init="False"/>
	<variable type="float" code="" init="0.0"/>
    </variables>
    <imports>
        <import>sys</import>
        <import>math</import>
    </imports>
    <code>
'''
{{ comments }}
'''

'''
{{ license }}
'''
{{ stdlib_imports }}

{{ static_methods }}


def main():
	 	{{local_var}}
	 	{{input_content}}
{{filtering_content}}
{{sink_content}}
{{exec_queries_content}}

if __name__ == '__main__':
        main()
    </code>
</template>

=== sedofihope/VTSG/tests/templates/test017/file_template.xml
<?xml version = "1.0" standalone="no"?>
<!DOCTYPE template SYSTEM "../dtd/file_template.dtd">
<!-- *created  "Fri Sep  9 16:05:23 2022" *by "Paul E. Black" -->
<!-- *modified "Mon Sep 12 09:15:43 2022" *by "Paul E. Black" -->

<!-- test fatal misuse of INDENT ... DEDENT in code -->
<!-- extra DEDENT -->
<template name="test017">
    <file_extension>py</file_extension>
    <comment>
        <open>'''</open>
        <close>'''</close>
        <inline>#</inline>
    </comment>
    <syntax>
      <!-- If language doesn't have a terminator, leave empty-->
      <statement_terminator></statement_terminator>
      <!-- Insert desired indentation level using spaces-->
      <indent>    </indent>
    </syntax>
    <namespace></namespace>
    <variables prefix="" import_code="import {{import_file}}">
        <variable type="int" code="" init="0"/>
        <variable type="string" code="" init="None"/>
	<variable type="bool" code="" init="False"/>
	<variable type="float" code="" init="0.0"/>
    </variables>
    <imports>
    </imports>
    <code>
'''
{{ comments }}
'''

'''
{{ license }}
'''
{{ stdlib_imports }}

{{ static_methods }}


def main():
    INDENT
    {{local_var}}
    {{input_content}}
    {{filtering_content}}
    {{sink_content}}
    DEDENT

DEDENT --- This one is unbalanced

if __name__ == '__main__':
        main()
    </code>
</template>

<!-- end of file_template.xml -->

=== sedofihope/VTSG/tests/templates/test027/file_template.xml
<?xml version = "1.0" standalone="no"?>
<!DOCTYPE template SYSTEM "../dtd/file_template.dtd">
<!-- *created  "Fri Jan 19 16:03:47 2024" *by "Paul E. Black" -->
<!-- *modified "Fri Jan 19 16:11:21 2024" *by "Paul E. Black" -->

<!-- test for imports from complexities and conditions -->

<template name="test027">
    <file_extension>py</file_extension>
    <comment>
        <open>'''</open>
        <close>'''</close>
        <inline>#</inline>
    </comment>
    <syntax>
      <!-- If language doesn't have a terminator, leave empty-->
      <statement_terminator></statement_terminator>
      <!-- Insert desired indentation level using spaces-->
      <indent>    </indent>
      <import_code>import {{import_file}}</import_code>
    </syntax>
    <variables prefix="">
    </variables>
    <code>
'''
VTSG test027
Test imports from complexities and conditions
{{ comments }}
'''

'''
{{ license }}
'''
{{ stdlib_imports }}

{{ static_methods }}


def main():
INDENT
    {{input_content}}
    {{filtering_content}}
    {{sink_content}}
    {{exec_queries_content}}
DEDENT

if __name__ == '__main__':
        main()
    </code>
</template>

<!-- end of file_template.xml -->
