=== sedofihope/VTSG/src/templates/dtd/file_template.dtd
<!-- file_template.dtd for VTSG -->
<!-- *modified "Thu Sep 12 11:10:54 2024" *by "Paul E. Black" -->
<!ELEMENT template (file_extension, comment, syntax, variables, imports?, code)>
<!ATTLIST template name CDATA #REQUIRED>
<!ELEMENT file_extension (#PCDATA)>
<!ELEMENT comment (open, close, inline)>
<!ELEMENT open (#PCDATA)>
<!ELEMENT close (#PCDATA)>
<!ELEMENT inline (#PCDATA)>
<!ELEMENT syntax (statement_terminator, indent?, import_code)>
<!ELEMENT statement_terminator (#PCDATA)>
<!ELEMENT indent (#PCDATA)>
<!ELEMENT import_code (#PCDATA)>
<!ELEMENT variables (variable*)>
<!ATTLIST variables prefix CDATA #REQUIRED>
<!ELEMENT variable EMPTY>
<!ATTLIST variable type CDATA #REQUIRED>
<!ATTLIST variable code CDATA #REQUIRED>
<!ATTLIST variable init CDATA #REQUIRED>
<!ELEMENT imports (import*)>
<!ELEMENT import (#PCDATA)>
<!ELEMENT code (#PCDATA)>
<!-- end of file_template.dtd -->

=== sedofihope/VTSG/src/templates/test011/file_template.xml
<?xml version = "1.0" standalone="no"?>
<!DOCTYPE template SYSTEM "../dtd/file_template.dtd">

<template name="test011">
    <file_extension>py</file_extension>
    <comment>
        <open>'''</open>
        <close>'''</close>
        <inline>#</inline>
    </comment>
    <namespace></namespace>
    <variables prefix="" import_code="import {{import_file}}">
        <variable type="int" code="" init="0"/>
        <variable type="string" code="" init="None"/>
	<variable type="bool" code="" init="False"/>
	<variable type="float" code="" init="0.0"/>
    </variables>
    <imports>
        <import>sys</import>
    </imports>
    <code>
'''
  Test 1 of 4 for statement_terminator
  No ang-syntax-ang at all.
'''
'''
{{ comments }}
'''

'''
{{ license }}
'''
{{ stdlib_imports }}

def main():
        {{ local_var }}
    
        {{ input_content }}

        {{ filtering_content }}

        {{ sink_content }}
    
        <!--{{ exec_queries_content }}-->

main()
{{ static_methods }}
    </code>
</template>

=== sedofihope/VTSG/tests/templates/test002/file_template.xml
<?xml version = "1.0" standalone="no"?>
<!DOCTYPE template SYSTEM "../dtd/file_template.dtd">
<!--  *created "Fri Nov  4 09:59:09 2022" *by "Paul E. Black" -->
<!-- *modified "Tue Jul 18 16:51:11 2023" *by "Paul E. Black" -->

<template name="test002">
    <file_extension>py</file_extension>
    <comment>
        <open>'''</open>
        <close>'''</close>
        <inline>#</inline>
    </comment>
    <syntax>
      <!-- If language doesn't have a terminator, leave empty-->
      <statement_terminator></statement_terminator>
      <!-- Insert desired indentation level using spaces-->
      <indent>    </indent>
    </syntax>
    <variables prefix="" import_code="import {{import_file}}">
        <variable type="int" code="" init="0"/>
        <variable type="string" code="" init="None"/>
	<variable type="bool" code="" init="False"/>
	<variable type="float" code="" init="0.0"/>
    </variables>
    <imports>
        <import>sys</import>
        <import>math</import>
    </imports>
    <code>
'''
  Test producing the same file name through different sets of modules.  The first
  generated case will be overwritten.
'''
'''
{{ comments }}
'''

'''
{{ license }}
'''
{{ stdlib_imports }}

{{ static_methods }}


def main():
    INDENT
    {{local_var}}
    {{input_content}}
    {{filtering_content}}
    {{sink_content}}
    {{exec_queries_content}}
    DEDENT

if __name__ == '__main__':
        main()
    </code>
</template>

=== sedofihope/VTSG/tests/templates/test020/file_template.xml
<?xml version = "1.0" standalone="no"?>
<!DOCTYPE template SYSTEM "../dtd/file_template.dtd">
<!-- *created  "Mon Feb 13 13:48:52 2023" *by "Paul E. Black" -->
<!-- *modified "Tue Aug  1 13:39:22 2023" *by "Paul E. Black" -->

<!-- test inconsistent declaring local variables, that is,
     mismatch between {{Local_var}} and <variable /> statements -->
<template name="test021">
    <file_extension>py</file_extension>
    <comment>
        <open>'''</open>
        <close>'''</close>
        <inline>#</inline>
    </comment>
    <syntax>
      <!-- If language doesn't have a terminator, leave empty-->
      <statement_terminator></statement_terminator>
      <!-- Insert desired indentation level using spaces-->
      <indent>    </indent>
      <import_code>import {{import_file}}</import_code>
    </syntax>
    <variables prefix="">
    </variables>
    <imports>
    </imports>
    <code>
'''
{{ comments }}
'''

'''
{{ license }}
'''
{{ stdlib_imports }}

{{ static_methods }}


def main():
    INDENT
    {{local_var}}
    {{input_content}}
    {{filtering_content}}
    {{sink_content}}
    DEDENT

if __name__ == '__main__':
        main()
    </code>
</template>

<!-- end of file_template.xml -->

=== sedofihope/VTSG/tests/templates/test014/file_template.xml
<?xml version = "1.0" standalone="no"?>
<!DOCTYPE template SYSTEM "../dtd/file_template.dtd">

<template name="test014">
    <file_extension>py</file_extension>
    <comment>
        <open>'''</open>
        <close>'''</close>
        <inline>#</inline>
    </comment>
    <syntax>
        <statement_terminator>;;</statement_terminator>
	<indent> ;-) </indent>
    </syntax>
    <namespace></namespace>
    <variables prefix="" import_code="import {{import_file}}">
        <variable type="int" code="" init="0"/>
        <variable type="string" code="" init="None"/>
	<variable type="bool" code="" init="False"/>
	<variable type="float" code="" init="0.0"/>
    </variables>
    <imports>
        <import>sys</import>
    </imports>
    <code>
'''
  Test 4 of 4 for statement_terminator
  two semicolons for statement_terminator
  Test INDENT...ENDINDENT code
'''
'''
{{ comments }}
'''

'''
{{ license }}
'''
{{ stdlib_imports }}

def main():
   INDENTanything after INDENT is ignored
   {{ local_var }}
    
        {{ input_content }}

        {{ filtering_content }}

        {{ sink_content }}
    
        <!--{{ exec_queries_content }} INDENT not at the start is ignored-->
ENDINDENT The indentation of INDENT and ENDINDENT do not matter

main()
{{ static_methods }}
    </code>
</template>

=== sedofihope/VTSG/tests/templates/test016/file_template.xml
<?xml version = "1.0" standalone="no"?>
<!DOCTYPE template SYSTEM "../dtd/file_template.dtd">
<!-- *created  "Fri Sep  9 16:05:23 2022" *by "Paul E. Black" -->
<!-- *modified "Tue Aug  1 13:38:19 2023" *by "Paul E. Black" -->

<template name="test016">
    <file_extension>py</file_extension>
    <comment>
        <open>'''</open>
        <close>'''</close>
        <inline>#</inline>
    </comment>
    <syntax>
      <!-- If language doesn't have a terminator, leave empty-->
      <statement_terminator></statement_terminator>
      <!-- Insert desired indentation level using spaces-->
      <indent>    </indent>
      <import_code>import {{import_file}}</import_code>
    </syntax>
    <variables prefix="">
        <variable type="int" code="" init="0"/>
        <variable type="string" code="" init="None"/>
	<variable type="bool" code="" init="False"/>
	<variable type="float" code="" init="0.0"/>
    </variables>
    <imports>
    </imports>
    <code>
'''
test fatal misuse of INDENT ... DEDENT in code: missing DEDENT
'''
'''
{{ comments }}
'''

'''
{{ license }}
'''
{{ stdlib_imports }}

{{ static_methods }}


def main():
INDENT
    {{local_var}}
    {{input_content}}
    {{filtering_content}}
    {{sink_content}}
DEDENT

if __name__ == '__main__':
        main()
    </code>
</template>

<!-- end of file_template.xml -->

=== sedofihope/VTSG/src/templates/php/file_template.xml
<?xml version = "1.0" standalone="no"?>
<!DOCTYPE template SYSTEM "../dtd/file_template.dtd">
<template name="PHP">
    <file_extension>php</file_extension>
    <comment>
        <open>/*</open>
        <close>*/</close>
        <inline>//</inline>
    </comment>
    <syntax>
      <statement_terminator>;</statement_terminator>
      <import_code>include "{{import_file}}";</import_code>
    </syntax>
    <variables prefix="$">
        <variable type="int" code="" init="0"/>
        <variable type="string" code="" init="null"/>
    </variables>
    <imports>
    </imports>
    <code>
        &lt;?php
        /*
        {{comments}}
        */

        /*
        {{license}}
        */
        {{stdlib_imports}}

        {{local_var}}
        {{input_content}}
        {{filtering_content}}
        {{sink_content}}
        {{exec_queries_content}}

        {{static_methods}}

        ?>
        </code>
</template>

=== sedofihope/VTSG/src/templates/py/file_template.xml
<?xml version = "1.0" standalone="no"?>
<!DOCTYPE template SYSTEM "../dtd/file_template.dtd">
<!-- *modified "Tue Aug  1 11:48:37 2023" *by "Paul E. Black" -->

<template name="Python">
    <file_extension>py</file_extension>
    <comment>
        <open>'''</open>
        <close>'''</close>
        <inline>#</inline>
    </comment>
    <syntax>
      <!-- If language doesn't have a terminator, leave empty-->
      <statement_terminator></statement_terminator>
      <!-- Insert desired indentation for one level -->
      <indent>    </indent>
      <import_code>import {{import_file}}</import_code>
    </syntax>
    <variables prefix="">
    </variables>
    <imports>
        <import>sys</import>
        <import>math</import>
    </imports>
    <code>
'''
{{ comments }}
'''

'''
{{ license }}
'''
{{ stdlib_imports }}

{{ static_methods }}


def main():
INDENT
    {{input_content}}
    {{filtering_content}}
    {{sink_content}}
    {{exec_queries_content}}
DEDENT

if __name__ == '__main__':
        main()
    </code>
</template>

<!-- end of file_template.xml -->

=== sedofihope/VTSG/tests/templates/test023/file_template.xml
<?xml version = "1.0" standalone="no"?>
<!DOCTYPE template SYSTEM "../dtd/file_template.dtd">
<!-- *created  "Fri Jun 30 16:13:47 2023" *by "Paul E. Black" -->
<!-- *modified "Tue Jul 18 16:49:10 2023" *by "Paul E. Black" -->

<template name="test023">
    <file_extension>py</file_extension>
    <comment>
        <open>'''</open>
        <close>'''</close>
        <inline>#</inline>
    </comment>
    <syntax>
      <!-- If language doesn't have a terminator, leave empty-->
      <statement_terminator></statement_terminator>
      <!-- Insert desired indentation level using spaces-->
      <indent>    </indent>
    </syntax>
    <variables prefix="" import_code="import {{import_file}}">
    </variables>
    <imports>
        <import>sys</import>
        <import>math</import>
    </imports>
    <code>
'''
VTSG test023
Test choosing cases using ACTS
{{ comments }}
'''

'''
{{ license }}
'''
{{ stdlib_imports }}

{{ static_methods }}


def main():
INDENT
    {{input_content}}
    {{filtering_content}}
    {{sink_content}}
    {{exec_queries_content}}
DEDENT

if __name__ == '__main__':
        main()
    </code>
</template>

<!-- end of file_template.xml -->
