=== sedofihope/VTSG/src/templates/dtd/filtering.dtd
<!-- filtering.dtd for VTSG -->
<!-- *modified "Thu Sep 12 11:56:54 2024" *by "Paul E. Black" -->
<!ELEMENT filtering (sample+)>
<!ELEMENT sample (path, comment, flaws, imports, code, input_type, output_type, options?)>
<!ELEMENT path (dir+)>
<!ELEMENT dir (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT flaws (flaw+)>
<!ELEMENT flaw EMPTY>
<!ATTLIST flaw flaw_type CDATA #REQUIRED>
<!ATTLIST flaw safe CDATA #REQUIRED>
<!ATTLIST flaw unsafe CDATA #REQUIRED>
<!ELEMENT imports (import*)>
<!ELEMENT import (#PCDATA)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT input_type (#PCDATA)>
<!ELEMENT output_type (#PCDATA)>
<!ELEMENT options EMPTY>
<!ATTLIST options need_complexity CDATA #IMPLIED>
<!-- end of filtering.dtd -->

=== sedofihope/VTSG/tests/templates/test011/filters.xml
<?xml version = "1.0" standalone="no"?>
<!DOCTYPE filtering SYSTEM "../dtd/filtering.dtd">
    <filtering>

        <sample>
            <path>
                <dir>no_filtering</dir>
            </path>
            <comment>no filtering</comment>
            <flaws>
                <flaw flaw_type="ALL" safe="0" unsafe="0"/>
            </flaws>
            <imports></imports>
            <code>
        <!--{% filter indent(8) -%}-->
        # No filtering (sanitization)
        {{out_var_name}} = {{in_var_name}}
        <!--{%- endfilter %}-->
            </code>
            <input_type>nofilter</input_type>
            <output_type>nofilter</output_type>
        </sample>

    </filtering>

=== sedofihope/VTSG/tests/templates/test020/filters.xml
<?xml version = "1.0" standalone="no"?>
<!-- *created  "Mon Feb 13 13:48:52 2023" *by "Paul E. Black" -->
<!-- *modified "Thu Mar  2 10:01:55 2023" *by "Paul E. Black" -->
<!DOCTYPE filtering SYSTEM "../dtd/filtering.dtd">
    <filtering>
        <sample>
            <path>
                <dir>none</dir>
            </path>
            <comment>no filtering</comment>
            <flaws>
                <flaw flaw_type="default" safe="0" unsafe="0"/>
            </flaws>
            <imports></imports>
            <code>
        # No filtering or sanitization
            </code>
            <input_type>nofilter</input_type>
            <output_type>nofilter</output_type>
        </sample>
    </filtering>

<!-- end of filtering.xml -->

=== sedofihope/VTSG/tests/templates/test016/filters.xml
<?xml version = "1.0" standalone="no"?>
<!-- *created  "Fri Sep  9 16:00:36 2022" *by "Paul E. Black" -->
<!-- *modified "Tue Mar 28 10:11:30 2023" *by "Paul E. Black" -->
<!DOCTYPE filtering SYSTEM "../dtd/filtering.dtd">
    <filtering>
        <sample>
            <path>
                <dir>none</dir>
            </path>
            <comment>no filtering</comment>
            <flaws>
                <flaw flaw_type="default" safe="0" unsafe="0"/>
            </flaws>
            <imports></imports>
            <code>
        # No filtering (sanitization)
        {{out_var_name}} = {{in_var_name}}
            </code>
            <input_type>string</input_type>
            <output_type>string</output_type>
        </sample>
    </filtering>

<!-- end of filtering.xml -->

=== sedofihope/VTSG/tests/templates/test009/filters.xml
<?xml version = "1.0" standalone="no"?>
<!DOCTYPE filtering SYSTEM "../dtd/filtering.dtd">
<!-- *created  "Wed Aug  2 10:27:34 2023" *by "Paul E. Black" -->
<!-- *modified "Wed Aug  2 10:27:40 2023" *by "Paul E. Black" -->
    <filtering>

        <sample>
            <path>
                <dir>no_filtering</dir>
            </path>
            <comment>no filtering</comment>
            <flaws>
                <flaw flaw_type="default" safe="0" unsafe="0"/>
            </flaws>
            <imports></imports>
            <code>
        # No filtering (sanitization)
        {{out_var_name}} = {{in_var_name}}
            </code>
            <input_type>nofilter</input_type>
            <output_type>nofilter</output_type>
	    <options need_complexity="0" />
        </sample>

        <sample>
            <path>
                <dir>no_filter</dir>
            </path>
            <!-- empty <comment></comment> -->
            <comment></comment>
            <flaws>
                <flaw flaw_type="IDS00-PL" safe="0" unsafe="0"/>
            </flaws>
            <imports></imports>
            <code>
        # No filtering (sanitization)
        {{out_var_name}} = {{in_var_name}}
            </code>
            <input_type>nofilter</input_type>
            <output_type>nofilter</output_type>
	    <options need_complexity="0" />
        </sample>

    </filtering>

=== sedofihope/VTSG/tests/templates/test025/filters.xml
<?xml version = "1.0" standalone="no"?>
<!DOCTYPE filtering SYSTEM "../dtd/filtering.dtd">
<!-- *modified "Fri Apr 14 10:27:55 2023" *by "Paul E. Black" -->
    <filtering>

        <sample>
            <path>
                <dir>no_filtering</dir>
            </path>
            <comment>no filtering</comment>
            <flaws>
                <flaw flaw_type="default" safe="0" unsafe="0"/>
            </flaws>
            <imports></imports>
            <code>
        # No filtering (sanitization)
        {{out_var_name}} = {{in_var_name}}
            </code>
            <input_type>nofilter</input_type>
            <output_type>nofilter</output_type>
	    <options need_complexity="0" />
        </sample>
        <sample>
            <path>
                <dir>remove_bad_chars_path</dir>
            </path>
            <comment>filter: remove all potentially dangerous characters from path</comment>
            <flaws>
                <flaw flaw_type="CWE_22" safe="1" unsafe="0"/>
            </flaws>
            <imports>
                <import>re</import>
            </imports>
            <code>
	      # remove any other characters
	      pattern = r'[^a-zA-Z0-9_ ,/]'
	      # lstrip removes any leading /
              {{out_var_name}} = re.sub(pattern, '', {{in_var_name}}).lstrip('/')
            </code>
            <input_type>string</input_type>
            <output_type>string</output_type>
        </sample>

    </filtering>

=== sedofihope/VTSG/tests/templates/test027/filters.xml
<?xml version = "1.0" standalone="no"?>
<!DOCTYPE filtering SYSTEM "../dtd/filtering.dtd">
<!-- *created  "Fri Jan 19 16:32:52 2024" *by "Paul E. Black" -->
<!-- *modified "Mon Jan 22 16:39:07 2024" *by "Paul E. Black" -->
    <filtering>
        <sample>
            <path>
                <dir>none</dir>
            </path>
            <comment>no filtering</comment>
            <flaws>
                <flaw flaw_type="default" safe="0" unsafe="0"/>
            </flaws>
            <imports></imports>
            <code>
        # No filtering (sanitization)
        {{out_var_name}} = {{in_var_name}}
            </code>
            <input_type>nofilter</input_type>
            <output_type>nofilter</output_type>
	    <options need_complexity="0" />
        </sample>

        <sample>
            <path>
                <dir>no_bad_chars</dir>
            </path>
            <comment>filter: remove all shell list or pipe operators</comment>
            <flaws>
                <flaw flaw_type="CWE78" safe="1" unsafe="0"/>
            </flaws>
            <imports>
                <import>re</import>
            </imports>
            <code>
	        # remove ||, &amp;&amp;, ;, &amp;, and |
	        pattern = '\|\||&amp;&amp;|[;&amp;|]'
                {{out_var_name}} = re.sub(pattern, '', {{in_var_name}})
            </code>
            <input_type>string</input_type>
            <output_type>string</output_type>
        </sample>
    </filtering>
<!-- end of filters.xml -->
