=== sedofihope/VTSG/src/templates/dtd/input.dtd
<!-- input.dtd for VTSG -->
<!-- *modified "Thu Sep 12 11:44:03 2024" *by "Paul E. Black" -->
<!ELEMENT input (sample+)>
<!ELEMENT sample (path, comment, flaws, imports?, code, input_type, output_type)>
<!ELEMENT path (dir+)>
<!ELEMENT dir (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT flaws (flaw+)>
<!ELEMENT flaw EMPTY>
<!ATTLIST flaw flaw_type CDATA #REQUIRED>
<!ATTLIST flaw safe CDATA #IMPLIED>
<!ATTLIST flaw unsafe CDATA #IMPLIED>
<!ELEMENT imports (import*)>
<!ELEMENT import (#PCDATA)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT input_type (#PCDATA)>
<!ELEMENT output_type (#PCDATA)>
<!-- end of input.dtd -->

=== sedofihope/VTSG/tests/templates/test025/inputs.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE input SYSTEM "../dtd/input.dtd">
<!-- *created  "Fri Apr 14 09:31:25 2023" *by "Paul E. Black" -->
<!-- *modified "Fri Apr 14 11:54:58 2023" *by "Paul E. Black" -->
    <input>
        <sample>
            <path>
                <dir>args</dir>
            </path>
            <comment>input: command line args</comment>
            <flaws>
                <flaw flaw_type="default" safe="0" unsafe="0"/>
            </flaws>
            <imports>
              <import>sys</import>
            </imports>
            <code>{{out_var_name}} = sys.argv[1]</code>
            <input_type>input: Command line args</input_type>
            <output_type>string</output_type>
        </sample>

        <sample>
            <path>
                <dir>hardcoded</dir>
            </path>
            <comment>input: hard coded string</comment>
            <flaws>
                <flaw flaw_type="OWASP_A01" safe="1" unsafe="0"/>
            </flaws>
            <imports>
            </imports>
            <code>{{out_var_name}} = 'hardcoded'</code>
            <input_type>input: hard coded string</input_type>
            <output_type>string</output_type>
        </sample>
    </input>

=== sedofihope/VTSG/tests/templates/test012/inputs.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE input SYSTEM "../dtd/input.dtd">
    <input>
        <sample>
            <path>
                <dir>hardcoded_string_input</dir>
            </path>
            <comment>Hardcoded string input</comment>
            <flaws>
                <flaw flaw_type="default" safe="1" unsafe="0"/>
            </flaws>
            <imports>
            </imports>
            <code>
        {{out_var_name}} = "." # local directory
            </code>
            <input_type>input : no input</input_type>
            <output_type>string</output_type>
        </sample>
    </input>

=== sedofihope/VTSG/tests/templates/test020/inputs.xml
<?xml version="1.0" standalone="no"?>
<!-- *created  "Mon Feb 13 13:48:24 2023" *by "Paul E. Black" -->
<!-- *modified "Mon Feb 13 13:48:36 2023" *by "Paul E. Black" -->
<!DOCTYPE input SYSTEM "../dtd/input.dtd">
    <input>
        <sample>
            <path>
                <dir>hardcoded_string</dir>
            </path>
            <comment>Hardcoded string input</comment>
            <flaws>
                <flaw flaw_type="default" safe="1" unsafe="0"/>
            </flaws>
            <imports>
            </imports>
            <code>{{out_var_name}} = "-d /;echo Vulnerability: user command run"</code>
            <input_type>input: no input</input_type>
            <output_type>string</output_type>
        </sample>
    </input>

<!-- end of input.xml -->

=== sedofihope/VTSG/tests/templates/example/inputs.xml
<?xml version="1.0" standalone="no"?>
<!-- *created  "Wed Sep 21 16:03:47 2022" *by "Paul E. Black" -->
<!-- *modified "Tue Sep 27 16:49:04 2022" *by "Paul E. Black" -->
<!DOCTYPE input SYSTEM "../dtd/input.dtd">
<!-- "language" for example used in the manual -->
    <input>
        <sample>
            <path>
                <dir>args</dir>
            </path>
            <comment>Command line args</comment>
            <flaws>
                <flaw flaw_type="default" safe="0" unsafe="0"/>
            </flaws>
            <imports>
            </imports>
            <code>
                {{out_var_name}} = args[1];
            </code>
            <input_type>input : Command line args</input_type>
            <output_type>string</output_type>
        </sample>
    </input>
<!-- end of input.xml -->

=== sedofihope/VTSG/tests/templates/test003/input.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE input SYSTEM "../dtd/input.dtd">
    <input>
        <sample>
            <path>
                <dir></dir>
            </path>
            <comment>Command line args</comment>
            <flaws>
                <flaw flaw_type="default" safe="0" unsafe="0"/>
            </flaws>
            <imports>
            </imports>
            <code>{{out_var_name}} = sys.argv[1]</code>
            <input_type>input : Command line args</input_type>
            <output_type>string</output_type>
        </sample>
    </input>

=== sedofihope/VTSG/src/templates/py/inputs.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE input SYSTEM "../dtd/input.dtd">
    <input>
        <!--
        <sample>
            <path>
                <dir></dir>
            </path>
            <comment></comment>
            <flaws>
                <flaw flaw_type="" safe=""/>
            </flaws>
            <imports>
                <import></import>
            </imports>
            <code></code>
            <input_type></input_type>
            <output_type></output_type>
        </sample>
        -->
<!--
        <sample>
            <path>
                <dir>shell_commands</dir>
            </path>
            <comment>input : shell commands</comment>
            <flaws>
                <flaw flaw_type="default" safe="0" unsafe="0"/>
            </flaws>
            <imports>
                <import>os</import>
            </imports>
            <code>os.system({{in_var_name}})</code>
            <input_type>string</input_type>
            <output_type></output_type>
        </sample>
-->
        <sample>
            <path>
                <dir>readline</dir>
            </path>
            <comment>input: direct user input in string</comment>
            <flaws>
                <flaw flaw_type="default" safe="0" unsafe="0"/>
            </flaws>
            <imports>
            </imports>
            <code>{{out_var_name}} = input()</code>
            <input_type>input : get user input in tainted</input_type>
            <output_type>string</output_type>
        </sample>

        <sample>
            <path>
                <dir>readline</dir>
            </path>
            <comment>input: integer from user input</comment>
            <flaws>
                <flaw flaw_type="default" safe="0" unsafe="0"/>
            </flaws>
            <imports>
            </imports>
            <code>
	    try:
	    INDENT
	        {{out_var_name}} = int(input())
	    DEDENT
	    except ValueError:
	    INDENT
	        {{out_var_name}} = 1776
	    DEDENT
	    </code>
            <input_type>input: get integer as tainted user input</input_type>
            <output_type>int</output_type>
        </sample>

        <sample>
            <path>
                <dir>none</dir>
            </path>
            <comment>No Input</comment>
            <flaws>
                <flaw flaw_type="default" safe="1" unsafe="0"/>
            </flaws>
            <imports>
            </imports>
            <code># no input</code>
            <input_type>input : no input</input_type>
            <output_type>none</output_type>
        </sample>

        <sample>
            <path>
                <dir>hardcoded_string</dir>
            </path>
            <comment>Hardcoded string as input</comment>
            <flaws>
                <flaw flaw_type="default" safe="1" unsafe="0"/>
            </flaws>
            <imports>
            </imports>
            <code>{{out_var_name}} = "-d /;echo Vulnerable: user command run"</code>
            <input_type>input : no input</input_type>
            <output_type>string</output_type>
        </sample>

        <sample>
            <path>
                <dir>hardcoded_integer</dir>
            </path>
            <comment>Hardcoded integer as input</comment>
            <flaws>
                <flaw flaw_type="CWE_369" safe="0" unsafe="0"/>
                <flaw flaw_type="default" safe="1" unsafe="0"/>
            </flaws>
            <imports>
            </imports>
            <code>{{out_var_name}} = 0</code>
            <input_type>input : no input</input_type>
            <output_type>int</output_type>
        </sample>

        <sample>
            <path>
                <dir>args</dir>
            </path>
            <comment>Command line args</comment>
            <flaws>
                <flaw flaw_type="default" safe="0" unsafe="0"/>
            </flaws>
            <imports>
            </imports>
            <code>{{out_var_name}} = sys.argv[1]</code>
            <input_type>input : Command line args</input_type>
            <output_type>string</output_type>
        </sample>

        <sample>
            <path>
                <dir>arg</dir>
            </path>
            <comment>input: integer from command line arg</comment>
            <flaws>
                <flaw flaw_type="default" safe="0" unsafe="0"/>
            </flaws>
            <imports>
            </imports>
            <code>
	    try:
	    INDENT
	        {{out_var_name}} = int(sys.argv[1])
	    DEDENT
	    except ValueError:
	    INDENT
	        {{out_var_name}} = 1776
	    DEDENT
	    </code>
            <input_type>input: integer from command line arg</input_type>
            <output_type>int</output_type>
        </sample>

        <sample>
            <path>
                <dir>env</dir>
            </path>
            <comment>input: environment variable</comment>
            <flaws>
                <flaw flaw_type="default" safe="0" unsafe="0"/>
            </flaws>
            <imports>
                <import>os</import>
            </imports>
            <code>{{out_var_name}} = os.environ['ADD']</code>
            <input_type>input: environment variable</input_type>
            <output_type>string</output_type>
        </sample>

        <sample>
            <path>
                <dir>env</dir>
            </path>
            <comment>input: integer from environment variable</comment>
            <flaws>
                <flaw flaw_type="default" safe="0" unsafe="0"/>
            </flaws>
            <imports>
                <import>os</import>
            </imports>
            <code>
	    try:
	    INDENT
	        {{out_var_name}} = int(os.environ['ADD'])
	    DEDENT
	    except ValueError:
	    INDENT
	        {{out_var_name}} = 1776
	    DEDENT
	    </code>
            <input_type>input: integer from environment variable</input_type>
            <output_type>int</output_type>
        </sample>

    <!-- Juliet has input from
	    File
	    PropertiesFile
	    Property
	    URLConnection
	    connect_tcp
	    listen_tcp
	    database
	    getCookies_Servlet
	    getParameter_Servlet
	    getQueryString_Servlet
    -->

    </input>

=== sedofihope/VTSG/tests/templates/test002/input.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE input SYSTEM "../dtd/input.dtd">
    <input>
        <sample>
            <path>
                <dir>hardcoded</dir>
            </path>
            <comment>input is hardcoded string</comment>
            <flaws>
                <flaw flaw_type="OWASP_A01" safe="1" unsafe="0"/>
            </flaws>
            <imports>
            </imports>
            <code>{{out_var_name}} = 'hardcoded string'</code>
            <input_type>input : Command line args</input_type>
            <output_type>string</output_type>
        </sample>
    </input>

=== sedofihope/VTSG/tests/templates/test027/inputs.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE input SYSTEM "../dtd/input.dtd">
<!-- *modified "Tue Jan 23 11:19:57 2024" *by "Paul E. Black" -->
<!-- *modified "Fri Jan 19 16:05:08 2024" *by "Paul E. Black" -->
    <input>
        <!--
        <sample>
            <path>
                <dir></dir>
            </path>
            <comment></comment>
            <flaws>
                <flaw flaw_type="" safe=""/>
            </flaws>
            <imports>
                <import></import>
            </imports>
            <code></code>
            <input_type></input_type>
            <output_type></output_type>
        </sample>
        -->
        <sample>
            <path>
                <dir>args</dir>
            </path>
            <comment>Command line args</comment>
            <flaws>
                <flaw flaw_type="default" safe="0" unsafe="0"/>
            </flaws>
            <imports>
	      <import>sys</import>
            </imports>
            <code>{{out_var_name}} = sys.argv[1]</code>
            <input_type>input: Command line args</input_type>
            <output_type>string</output_type>
        </sample>

    </input>

<!-- end of inputs.xml -->
