=== sedofihope/VTSG/src/templates/dtd/sink.dtd
<!-- sink.dtd for VTSG -->
<!-- *modified "Thu Sep 12 11:53:26 2024" *by "Paul E. Black" -->
<!ELEMENT sink (sample+)>
<!ELEMENT sample (path, flaw_type, comment, imports?, code, safety, input_type, exec_type)>
<!ELEMENT path (dir+)>
<!ELEMENT dir (#PCDATA)>
<!ELEMENT flaw_type (#PCDATA)>
<!ATTLIST flaw_type flaw_group CDATA #REQUIRED>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT imports (import*)>
<!ELEMENT import (#PCDATA)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT safety EMPTY>
<!ATTLIST safety safe CDATA #REQUIRED>
<!ATTLIST safety unsafe CDATA #REQUIRED>
<!ELEMENT input_type (#PCDATA)>
<!ELEMENT exec_type (#PCDATA)>
<!-- end of sink.dtd -->

=== sedofihope/VTSG/tests/templates/test007/sinks.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE sink SYSTEM "../dtd/sink.dtd">
    <sink>

        <sample>
            <path>
                <dir>file_exists</dir>
            </path>
            <flaw_type>ERR01-J</flaw_type>
            <comment>sink: check if a file exists</comment>
            <imports>
                <import>os</import>
            </imports>
            <code>
	{{flaw}}
        os.path.exists({{in_var_name}})</code>
            <safety safe="0" unsafe="0"/>
            <input_type>string</input_type>
            <exec_type>none</exec_type>
        </sample>

    </sink>

=== sedofihope/VTSG/tests/templates/example/sink.xml
<?xml version="1.0" standalone="no"?>
<!-- *created  "Wed Sep 21 16:03:47 2022" *by "Paul E. Black" -->
<!-- *modified "Wed Sep 21 16:50:31 2022" *by "Paul E. Black" -->
<!DOCTYPE sink SYSTEM "../dtd/sink.dtd">
<!-- "language" for example used in the manual -->
    <sink>
        <sample>
            <path>
                <dir>select_from</dir>
                <dir>concatenation_simple_quote</dir>
            </path>
            <flaw_type flaw_group="OWASP_a1">CWE_89</flaw_type>
            <comment>construction : concatenation with simple quote</comment>
            <imports></imports>
            <code>
                {{flaw}}
                string query = "SELECT * FROM '" + {{in_var_name}} + "'";
            </code>
            <safety safe="0" unsafe="0"/>
            <input_type>string</input_type>
            <exec_type>SQL</exec_type>
        </sample>
    </sink>
<!-- end of sink.xml -->

=== sedofihope/VTSG/tests/templates/test010/sink.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE sink SYSTEM "../dtd/sink.dtd">
    <sink>

        <sample>
            <path>
                <dir>file_exists</dir>
            </path>
            <flaw_type flaw_group="OWASP_a4">CWE_22</flaw_type>
            <comment>sink: check if a file exists</comment>
            <imports>
                <import>os</import>
            </imports>
            <code>
	'''
	    no curly-curly-flaw-curly-curly line
	'''
        os.path.exists({{in_var_name}})</code>
            <safety safe="0" unsafe="0"/>
            <input_type>string</input_type>
            <exec_type>none</exec_type>
        </sample>

        <sample>
            <path>
                <dir>file_exists</dir>
            </path>
	    <!-- Use SEI CERT flaw name -->
            <flaw_type flaw_group="OWASP_a4">IDS00-PL</flaw_type>
            <comment>sink: check if a file exists</comment>
            <imports>
                <import>os</import>
            </imports>
            <code>
	{{flaw}}
        os.path.exists({{in_var_name}})</code>
            <safety safe="0" unsafe="0"/>
            <input_type>string</input_type>
            <exec_type>none</exec_type>
        </sample>

        <sample>
            <path>
                <dir>ls</dir>
            </path>
	    <!-- different group, same flaw type as above -->
            <flaw_type flaw_group="Zarahemla">CWE_22</flaw_type>
            <comment>sink: run ls in a dir</comment>
            <imports>
                <import>os</import>
            </imports>
            <code>
        {{flaw}}
        os.system('ls ' + {{in_var_name}});
            </code>
            <safety safe="0" unsafe="0"/>
            <input_type>string</input_type>
            <exec_type>none</exec_type>
        </sample>

    </sink>

=== sedofihope/VTSG/src/templates/test017/sink.xml
<?xml version="1.0" standalone="no"?>
<!-- *created  "Fri Sep  9 16:00:36 2022" *by "Paul E. Black" -->
<!-- *modified "Fri Sep  9 16:04:37 2022" *by "Paul E. Black" -->
<!DOCTYPE sink SYSTEM "../dtd/sink.dtd">
    <sink>
        <sample>
            <path>
                <dir>ls</dir>
            </path>
            <flaw_type flaw_group="OWASP_a1">CWE_78</flaw_type>
            <comment>sink: run ls in a dir</comment>
            <imports>
                <import>os</import>
            </imports>
            <code>
        {{flaw}}
        os.system('ls ' + {{in_var_name}})
            </code>
            <safety safe="0" unsafe="0"/>
            <input_type>string</input_type>
            <exec_type>none</exec_type>
        </sample>
    </sink>

<!-- end of sink.xml -->

=== sedofihope/VTSG/tests/templates/test011/sink.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE sink SYSTEM "../dtd/sink.dtd">
    <sink>
        <sample>
            <path>
                <dir>file_exists</dir>
            </path>
            <flaw_type flaw_group="OWASP_a4">CWE_22</flaw_type>
            <comment>sink: check if a file exists</comment>
            <imports>
                <import>os</import>
            </imports>
            <code>
                <!--{% filter indent(8) %}
                {{flaw}}-->
        print(os.path.exists({{in_var_name}}))
                <!--{% endfilter %}-->
            </code>
            <safety safe="0" unsafe="0"/>
            <input_type>string</input_type>
            <exec_type>none</exec_type>
        </sample>
    </sink>

=== sedofihope/VTSG/tests/templates/test025/sinks.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE sink SYSTEM "../dtd/sink.dtd">
<!-- *created  "Fri Apr 14 09:31:25 2023" *by "Paul E. Black" -->
<!-- *modified "Fri Apr 14 11:54:47 2023" *by "Paul E. Black" -->
    <sink>
        <sample>
            <path>
                <dir>file_exists</dir>
            </path>
            <flaw_type flaw_group="OWASP_a4">CWE_22</flaw_type>
            <comment>sink: check if a file exists</comment>
            <imports>
                <import>os</import>
            </imports>
            <code>
	      {{flaw}}
              os.path.exists({{in_var_name}})
	    </code>
            <safety safe="0" unsafe="0"/>
            <input_type>string</input_type>
            <exec_type>none</exec_type>
        </sample>

        <sample>
            <path>
                <dir>file_exists</dir>
            </path>
	    <!-- Use SEI CERT flaw name -->
            <flaw_type flaw_group="OWASP_a4">IDS00-PL</flaw_type>
            <comment>sink: check if a file exists</comment>
            <imports>
                <import>os</import>
            </imports>
            <code>
	{{flaw}}
        os.path.exists({{in_var_name}})</code>
            <safety safe="0" unsafe="0"/>
            <input_type>string</input_type>
            <exec_type>none</exec_type>
        </sample>

        <sample>
            <path>
                <dir>ls</dir>
            </path>
	    <!-- different group, same flaw type as above -->
            <flaw_type flaw_group="Zarahemla">CWE_22</flaw_type>
            <comment>sink: run ls in a dir</comment>
            <imports>
                <import>os</import>
            </imports>
            <code>
        {{flaw}}
        os.system('ls ' + {{in_var_name}});
            </code>
            <safety safe="0" unsafe="0"/>
            <input_type>string</input_type>
            <exec_type>pass</exec_type>
        </sample>

        <sample>
            <path>
                <dir>file_exists</dir>
            </path>
	    <!-- missing flaw_group -->
            <flaw_type>OWASP_A01</flaw_type>
	    <!-- no <comment></comment> -->
            <imports>
                <import>os</import>
            </imports>
            <code>
        print(f'file "{ {{in_var_name}} }" ', end='')
        {{flaw}}
        if os.path.exists({{in_var_name}}):
	INDENT
            print('exists')
	DEDENT
	else:
	INDENT
            print('does not exist')
	DEDENT
	    </code>
            <safety safe="0" unsafe="0"/>
            <input_type>string</input_type>
            <exec_type>none</exec_type>
        </sample>

        <sample>
            <path>
                <dir>info_expose</dir>
            </path>
            <flaw_type flaw_group="OWASP_a5">CWE_209</flaw_type>
            <comment>sink: information exposure</comment>
            <imports>
            </imports>
            <code>
	        # find a sum that the compiler won't predict
                intArray = sorted([2, 37, 849, 24, 42, -10, 93])
		for nb in intArray:
		INDENT
                    r = nb + 3
                    num = r / 10
                    sum = num + nb
                    print(f'Current sum: {sum}')
		DEDENT
                try:
		INDENT
                    a = 0
                    b = 1
		    # sum is a float, so range(sum) throws TypeError
                    for i in range(sum):
		    INDENT
		        (a, b) = (b, a + b)
		    DEDENT
                    print(f'{sum}th Fibonacci number is {a}')
		DEDENT
                except TypeError as te:
		INDENT
                    {{flaw}}
                    print(f'TypeError: {te}: for i in range({sum}):') # leaks value of sum
		DEDENT
            </code>
            <safety safe="0" unsafe="1"/>
	    <!-- no input (or filter) needed -->
            <input_type>none</input_type>
            <exec_type>none</exec_type>
        </sample>

    </sink>

=== sedofihope/VTSG/tests/templates/test002/sink.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE sink SYSTEM "../dtd/sink.dtd">
    <sink>

        <sample>
            <path>
                <dir>file_exists</dir>
            </path>
            <flaw_type flaw_group="OWASP_a4">IDS00-PL</flaw_type>
            <comment>sink: check if a file exists</comment>
            <imports>
                <import>os</import>
            </imports>
            <code>
	{{flaw}}
        os.path.exists({{in_var_name}})</code>
            <safety safe="0" unsafe="0"/>
            <input_type>string</input_type>
            <exec_type>none</exec_type>
        </sample>

        <sample>
            <path>
	        <!-- repeated <dir> yields the same file name, overwriting previous cases -->
                <dir>file_exists</dir>
            </path>
            <flaw_type flaw_group="OWASP_a4">IDS00-PL</flaw_type>
            <comment>second sink: check if a file exists</comment>
            <imports>
                <import>os</import>
            </imports>
            <code>
        print(f'file "{ {{in_var_name}} }" ', end='')
        {{flaw}}
        if os.path.exists({{in_var_name}}):
	INDENT
            print('exists')
	DEDENT
	else:
	INDENT
            print('does not exist')
	DEDENT
	    </code>
            <safety safe="0" unsafe="0"/>
            <input_type>string</input_type>
            <exec_type>none</exec_type>
        </sample>

    </sink>

=== sedofihope/VTSG/tests/templates/test027/sinks.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE sink SYSTEM "../dtd/sink.dtd">
<!-- *created  "Fri Jan 19 16:18:22 2024" *by "Paul E. Black" -->
<!-- *modified "Mon Jan 22 16:44:07 2024" *by "Paul E. Black" -->
    <sink>
        <sample>
            <path>
                <dir>ls</dir>
            </path>
            <flaw_type flaw_group="OWASP_a1">CWE78</flaw_type>
            <comment>sink: run ls
&lt;&lt; POV
-d / | echo Vulnerable: user command run
POV</comment>
            <imports>
                <import>os</import>
            </imports>
            <code>
        {{flaw}}
        os.system('ls ' + {{in_var_name}})
            </code>
            <safety safe="0" unsafe="0"/>
            <input_type>string</input_type>
            <exec_type>none</exec_type>
        </sample>
    </sink>
<!-- end of sinks.xml -->
